# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.1]
forge_version=47.4.0
forge_version_range=[47,)
mapping_channel=official

## Mod Properties
mod_id=brewersdelight
mod_name=BrewersDelight
mod_displayName=Brewer's Delight
mod_license=MIT
mod_version=0.7.0-rc1
mod_group_id=pupkin.brewersdelight
mod_authors=pupkin2001
mod_url=https://github.com/pupkin2001/brewersdelight/
mod_description=Brewer's Delight is an add-on for Farmer's Delight and Brewin' and Chewin' adding more beverages.
mod_credits=Parts of the code, as well as some palettes and texture shapes were used or inspired by both required modifications to better match them functionally and visually.

# Dependency Properties
# Hard dependencies
farmersdelight_version=6917255
farmersdelight_version_range=[1.2.2,)
# Brewin' and Chewin' doesn't have a stable release for 1.20.1
# Using local 1.20.1 build until released.
# Version above 1.20.1 seem to be unsupported.
brewinandchewin_version=6237884
brewinandchewin_version_range=[1.20.1-3.0.0,)

# Soft dependencies
corn_delight_version=6904187
corn_delight_version_range=[1.0.3,)
mmlib_version=7154351
cropotopia_version=4997459
cropotopia_version_range=[2.3.0,)
epherolib_version=4889101

# Runtime dependency (for testing)
jei_version=6600311
appleskin_version=4770828
