# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
# A version range to match for said mod loader
loaderVersion = "${forge_version_range}"
# The license for you mod.
license = "${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "${mod_url}issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId = "${mod_id}"
# The version number of the mod
version = "${mod_version}"
# A display name for the mod
displayName = "${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="${mod_url}"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="assets/brewersdelight/textures/logo.png"
# A text field displayed in the mod UI
credits="${mod_credits}"
# A text field displayed in the mod UI
authors = "${mod_authors}"
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
displayTest="MATCH_VERSION"

# The description text for the mod (multi line!)
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true
# The version range of the dependency
versionRange = "${forge_version_range}"
# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "farmersdelight"
mandatory = true
versionRange = "${farmersdelight_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "brewinandchewin"
mandatory = true
versionRange = "${brewinandchewin_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "corn_delight"
mandatory = false
versionRange = "${corn_delight_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "cropotopia"
mandatory = false
versionRange = "${cropotopia_version_range}"
ordering = "BEFORE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"