name: Pull Request Check

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-PR${{github.event.number}}-${{ hashFiles('**/build.gradle', 'gradle/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('gradle/gradle-wrapper.properties', 'settings.gradle.kts', '**/build.gradle.kts', '**/gradle.properties') }}
            ${{ runner.os }}-gradle-PR${{github.event.number}}-
            ${{ runner.os }}-gradle-

      - name: Initialize gradlew
        run: ./gradlew

      - name: Build
        run: ./gradlew build
