name: Test

on: [ pull_request, push ]

jobs:
  duplicate_check:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

  build-dependency:
    name: Build Dependency
    needs: duplicate_check
    if: needs.duplicate_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Dependency Repository
        uses: actions/checkout@v4
        with:
          repository: wiidotmom/BrewinAndChewin

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Dependency Gradle
        id: cache-dep
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            ~/gradle
          key: ${{ runner.os }}-dep-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-dep-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
            ${{ runner.os }}-dep-gradle-

      - name: Grant Permissions to Gradlew
        run: chmod +x ./gradlew

      - name: Initialize Dependency Gradlew
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: ./gradlew

      - name: Build Dependency
        run: ./gradlew build

      - name: Capture Dependency Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: brewinandchewin
          path: build/libs/
          if-no-files-found: error
          retention-days: 7

  build:
    name: Build
    needs: [ duplicate_check, build-dependency ]
    if: needs.duplicate_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore Gradle Cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle
            ~/gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
            ${{ runner.os }}-gradle-

      - name: Download Dependency Artifact
        uses: actions/download-artifact@v4
        with:
          name: brewinandchewin
          path: ./libs

      - name: Grant Permissions to Gradlew
        run: chmod +x ./gradlew

      - name: Generate Resources
        run: ./gradlew runData

      - name: Cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle
            ~/gradle
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: ./gradlew build

      - name: Capture Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: brewersdelight
          path: build/libs/
          if-no-files-found: error
          retention-days: 7